# 1. Python Level 1

### Shortcuts

Mostrar combinaciones de teclas :Ctrl+M+H

Ejecutar Celda: Ctrl/Cmd +Enter <br>
Ejecutar Celda y pasar a la siguiente: Shift + Enter <br>
Ejecutar Celda y crear una nueva: Alt+Enter <br>
Ejecutar Selección: Ctrl/Cmd+Shift+Enter <br>
Ejecutar todas las celdas: Ctrl/Cmd + F9 <br>
Guardar bloc de notas: Ctrl/Cmd+S <br>
Interrumpir la ejecución: Ctrl + M + I

Insertar celda de código arriba:Ctrl + M+ A <br>
Insertar celda de código abajo: Ctrl + M+ B <br>
Borrar Celda: Ctrl/Cmd+M+D <br>
Deshacer la última acción de las celdas : Ctrl + M +  Z <br>




Convertir a celda de código: Ctrl+M+Y <br>
Convertir a celda de texto: Ctrl+M+M <br>


### Hoja de trucos de Markdown

https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

## 1.1 Números

In [0]:
# comentar con el símbolo gato dentro de una celda de código
1+3

4

In [0]:
2**(1/2)

1.4142135623730951

In [0]:
#asignar una variable
a = 45
a

45

In [0]:
#reasignar una variable
a=a+1
a

46

In [0]:
#Como 2 cae un número entero de veces en 4 su resto es 0
4%2

0

In [0]:
#Pero 3 no 
4%3

1

## 1.2 Strings
Un string es una cadena de caracteres y se inicializa poniendo contenido entre comillas simples o dobles

In [0]:
'hola2131232'

'hola2131232'

In [0]:
#cuidado con los apóstrofes
'isn't'

SyntaxError: ignored

In [0]:
#forma correcta
"isn't"

"isn't"

In [0]:
#largo de un string
len('hola ')

5

In [0]:
#asignación de variables
# el espacio se considera como un carácter 
a='hola mundo'
a

'hola mundo'

In [0]:
# OJO! python parte desde el 0, por ende la primera posición es el 0
#acceder a un elmento específico 
a[0]

'h'

In [0]:
#último carácter
a[-1]

'o'

In [0]:
#mostrar todos los elementos
a[:]

'hola mundo'

In [0]:
#mostrar todos los elementos menos el penúltimo
a[:-1]

'hola mund'

In [0]:
#todos los elementos entre la posición 2 y 4
a[1:4]

'ola'

In [0]:
# ERROR: índice fuera de rango, si el largo del string es 10, sus posiciones van del 0 al 9
a[10]

IndexError: ignored

In [0]:
#ERROR: Los caracteres de un string son inmuntables
a[0]='H'

TypeError: ignored

In [0]:
#Concatenar
'Hola' + ' Kevin' +' Murphy'

'Hola Kevin Murphy'

In [0]:
#Formatear un string

'Nombre: {n}, Apellido:{a}'.format(n='Kevin', a='Murphy')

'Nombre: Kevin, Apellido:Murphy'

## 1.3 Listas
Una lista es conjunto ordenado de elementos

In [0]:
#Una lista puede tener diferentes tipos de objetos
my_list = [1, 'hola', '2', [1, 2, 3]]
my_list

[1, 'hola', '2', [1, 2, 3]]

In [0]:
#indexamiento
print('posicion 0: ',my_list[0], '\n')
print('todos los elementos: ',my_list[:], '\n')
print('todos los elementos menos el último: ',my_list[:-1], '\n')
print('indexar un elemento dentro de la lista: ',my_list[3][1], '\n') #la posición 2 del elemento 4 de la lista

posicion 0:  1 

todos los elementos:  [1, 'hola', '2', [1, 2, 3]] 

todos los elementos menos el último:  [1, 'hola', '2'] 

indexar un elemento dentro de la lista:  2 



In [0]:
#Los elementos de una lista son mutables
my_list[1] = 'Hello World'
my_list

[1, 'Hello World', '2', [1, 2, 3]]

In [0]:
#agregar un elemento a la lista
my_list.append(0)
my_list

[1, 'Hello World', '2', [1, 2, 3], 0]

In [0]:
#Eliminar un elemento de la lista
my_list.pop(0) #eliminar la posición 0
my_list

['Hello World', '2', [1, 2, 3]]

In [0]:
print(len(my_list))#Largo de una lista
print(len(my_list[2]))#Largo de un elmento de la lista

3
3


## 1.4 Diccionarios

Un diccionario es un conjunto no ordenado de elementos, cada elemento tiene una llave para acceder a este un valor asociado a esa llave

diferentes tipos de datos<br>
indexamientos<br>
agregar elementos<br>
lista de llaves y valores <br>

In [0]:
#Los valores de las llaves pueden ser un número o un string, los valores pueden ser cualquier tipo de elemento
my_dict = {'key1':9, 'key2':[1,2,3], 'key3': 'hola', 99:'número', 'key5': {'k1': 'nested_value1', 'k2':'nested_value2'}}
my_dict

{99: 'número',
 'key1': 9,
 'key2': [1, 2, 3],
 'key3': 'hola',
 'key5': {'k1': 'nested_value1', 'k2': 'nested_value2'}}

In [0]:
#ERROR: Los diccionarios se indexan por sus llaves
my_dict[0]

KeyError: ignored

In [0]:
my_dict['key1']

9

In [0]:
#lista que las llaves
list(my_dict.keys())

['key1', 'key2', 'key3', 99, 'key5']

In [0]:
#lista de los valores
list(my_dict.values())

[9,
 [1, 2, 3],
 'hola',
 'número',
 {'k1': 'nested_value1', 'k2': 'nested_value2'}]

In [0]:
#Agregar un elmento
my_dict['key4'] = 'hi'

In [0]:
my_dict

{99: 'número',
 'key1': 9,
 'key2': [1, 2, 3],
 'key3': 'hola',
 'key4': 'hi',
 'key5': {'k1': 'nested_value1', 'k2': 'nested_value2'}}

## 1.5 Tuplas

Las tuplas son conjuntos ordenados al igual que las listas, pero no son mutables.

In [0]:
my_tupla = (1, 'hola')
my_tupla

(1, 'hola')

In [0]:
my_tupla[0]

1

In [0]:
#ERROR: los elementos de una tupla no son mutables
my_tupla[0]='hi'

TypeError: ignored

In [0]:
#ERROR:la tupla no es mutable, no se puede agregar elementos a la lista
my_tupla.append('hola')

AttributeError: ignored

## 1.6 Conjuntos
Los conjuntos continen una serie de elementos al igual que las listas, pero son no ordenados y cada elemento del conjunto es único. Además sus elementos solo pueden ser números o strings.

colecciones no ordenadas, elementos únicos<br>
añadir elementos : add() <br>
interseccion: intersection()<br>
union: union() <br>
resta de conjuntos<br>

In [0]:
#ERROR: solo objetos tipo número o string, NO listas, tuplas, diccionarios, etc.
{1, 'hola', [1,2]}

TypeError: ignored

In [0]:
#Elementos únicos
{1, 2, 2, 3, 3}

{1, 2, 3}

In [0]:
#Crear un conjunto a partir de una lista. Python tiene mucha flexibilidad para pasar de un objeto a otro objeto, por ejemplos de listas a tuplas, listas a conjuntos, etc.
set([1, 2, 2, 3])

{1, 2, 3}

In [0]:
A = {1, 2, 3}
B = {2, 3, 4}

In [0]:
print('Elementos que están en A y que NO están en B: ', A-B, '\n')
print('Elementos que están en A y  en B: ', A.intersection(B), '\n')
print('Unión de A y B: ', A.union(B), '\n')

Elementos que están en A y que NO están en B:  {1} 

Elementos que están en A y  en B:  {2, 3} 

Unión de A y B:  {1, 2, 3, 4} 

Elementos que están en A y que NO están en B:  {1} 



## 1.7 Booleanos

Valores posibles de un objeto booleano: True, False, None <br>

Documentación:<br>
https://docs.python.org/3.7/library/stdtypes.html

In [0]:
a = True
a

True

In [0]:

b = False
b

False

In [0]:
a == b # a es igual a b?

False

In [0]:
a != b #a es distinto de b?

True

In [0]:
A = 1
B = 2

print('Es A mayor estricto que B?: ', a > b, '\n') 
print('Es A es menor o igual que B que B?: ', a <= b) 

Es A mayor estricto que B?:  False 

Es A es menor o igual que B que B?:  True


## 1.8 Control del flujo

Una estructura de control, es un bloque de código que permite agrupar instrucciones de manera controlada.

Para describir la evaluación a realizar sobre una condición, se utilizan operadores relacionales (o de comparación):<br>



$==$	Igual que<br>
$!=$	Distinto que<br>
$<$	Menor que	<br>
$>$	Mayor que	<br>
$<=$	Menor o igual que	 <br>
$>=$	Mayor o igual que	 <br>


<br>
Y para evaluar más de una condición simultáneamente, se utilizan operadores lógicos:<br>

Operar "Y" : "and" o "&""<br>
Operador "O": "or" o  ""|""<br>
Operador "O exclusivo": "xor"<br>
if/elif/else<br>



Las estructuras de control de flujo condicionales, se definen mediante el uso de tres palabras claves reservadas, del lenguaje:<br>
if (si), elif (sino, si) y else (sino).<br><br>


Más documentación:

https://librosweb.es/libro/python/capitulo-2/estructuras-de-control-de-flujo.html

In [0]:
a = 2
b = 1

In [0]:
if a < b: 
  print('se cumplió la instrucción 1')
elif a == b:
  print('no se cumplió la instrucción 1, pero si la 2')
else:
  print('no se cump8lió ninguna de las instrucciones anteriores')

no se cumplió ninguna de las instrucciones anteriores


## 1.9 Loops

Un loops ejecuta una secuencia de declaraciones varias veces.



  

In [0]:
#Devuelve un objeto que produce una secuencia de enteros desde el inicio (inclusive) detener (exclusivo) por pasos
print(range(5),': ', list(range(5))) # entre 0 y 5
print(range(1,5),': ', list(range(1,5))) # entre 0 y 5
print(range(2,11, 2), ': ', list(range(2,11, 2))) # entre 2 y 11 con saltos de 2 en 2 

range(0, 5) :  [0, 1, 2, 3, 4]
range(1, 5) :  [1, 2, 3, 4]
range(2, 11, 2) :  [2, 4, 6, 8, 10]
range(2, 11, -1) :  []


In [0]:
# Ejecutar un declaración tantas veces como el largo de la secuencia range(5)
for i in range(5):
  n_iteracion = i+1
  print('rango: {elem_rango}, iteración: {n_iteracion}'.format(elem_rango=i, n_iteracion=n_iteracion))

rango: 0, iteración: 1
rango: 1, iteración: 2
rango: 2, iteración: 3
rango: 3, iteración: 4
rango: 4, iteración: 5


In [0]:
my_list = [5, 6, 7, 8, 9]

In [0]:
# Ejecutar un declaración tantas veces como el largo de la lista
for i in range(len(my_list)):
  print('posición: {posicion}, elemento: {elem}'.format(posicion=i, elem=my_list[i])) 

posición: 0, elemento: 5
posición: 1, elemento: 6
posición: 2, elemento: 7
posición: 3, elemento: 8
posición: 4, elemento: 9


In [0]:
for i, elem in enumerate(my_list):
  print('posición: ', i, 'elemento: ', elem)

posición:  0 elemento:  5
posición:  1 elemento:  6
posición:  2 elemento:  7
posición:  3 elemento:  8
posición:  4 elemento:  9


In [0]:
for elem in my_list: 
  elem_x2 = elem*2
  print('elemento: {elem}, elemento por 2: {elem_x2}'.format(elem=elem, elem_x2=elem_x2))

elemento: 5, elemento por 2: 10
elemento: 6, elemento por 2: 12
elemento: 7, elemento por 2: 14
elemento: 8, elemento por 2: 16
elemento: 9, elemento por 2: 18


In [0]:
#Ejecutar una declaración hasta que se cumpla la condición de parada, es decir 'while (condition) ==False'
i=0
while (i<10):
  print('iteración:', i)
  i=i+1
  

iteración: 0
iteración: 1
iteración: 2
iteración: 3
iteración: 4
iteración: 5
iteración: 6
iteración: 7
iteración: 8
iteración: 9


# 2. Python Level 2

## 2.1 Funciones


Para definir una función se usa la siguiente sintaxis:


```
  def nombre_funcion(inputs):
      declaraciones ....
```

```
  def nombre_funcion(x, y, z=default):
      declaraciones ....
  
  #formas de ejecutar función
  nombre_funcion(a, b)
 
  nombre_funcion(x=a, y=b)
 
  nombre_funcion(x=a, y=b, z=c)
```

Variables mágicas usadas para definir funciones:

. *args se utiliza para pasar una lista de argumentos.<br>
**kwargs para pasar un diccionario de argumentos, sirve para manejar los argumentos por nombre.<br>

Más documentación:<br>
https://pythontips.com/2013/08/04/args-and-kwargs-in-python-explained/ <br>


In [0]:
def my_funct(): #una función puede no recibir parámetros
  print('hola mundo')
  

my_funct() #ejecución

hola mundo


In [0]:
def saludo(nombre):
  print('Hola', nombre)

In [0]:
saludo('K.Murpphy')

Hola K.Murpphy


In [0]:
def my_funct(x):
  if x>0:
    return 'número positivo'
  else:
    return 'número no positivo'

In [0]:
my_funct(1)

'número positivo'

In [0]:
my_list = [1, 2, 3, 4]
def suma(x):
  sum=0
  for elem in x:
    sum=sum+elem
  return sum

suma(my_list)

10

In [0]:
def minimo(x):
  N = len(x)
  min_value = x[0]
  
  i = 0

  for elem in x: #recorrer los elementos en x
    if min_value > elem: #si el valor mínimo actual es mayor estricto que el elemento de la iteración actual
      min_value = elem #actualizar valor mínimo
    else: #esta línea se puede omitir
      min_value = min_value
      
  return min_value

minimo(my_list)

1

In [0]:
def maximo(x):
  N = len(x)
  max_value = x[0]
  
  i = 0

  for elem in x: 
    if max_value < elem: 
       max_value = elem 
    else: 
      max_value = max_value
      
  return max_value

maximo(my_list)

4

$$\bar{X} = \frac{\sum_{i=1}^{N} x_{i}}{N}$$

In [0]:
def promedio(x):
  N=len(x)
  return sum(x)/N

promedio(my_list)

2.5

$$\sigma = \sqrt{\frac{\sum_{i=1}^{N} (x_{i}-\bar{X})^{2}}{N}}$$

In [0]:
def desviacion(x):
  N = len(x)
  
  mean = promedio(x)
  sum_diff_2 = 0 #suma de las desviaciones cuadradas con respecto a la media
  for elem in x:
    sum_diff_2 = sum_diff_2 + (elem-mean)**2
    
  sigma = (sum_diff_2/N)**(1/2)
  return sigma

desviacion(my_list)

1.118033988749895


## 2.2 Scope

El* scope* o alcance de una variable se refiere a los lugares en que se puede ver o acceder a una variable.

In [0]:
#Las variables definidas dentro de una función no tienen impacto en las variables definidas a fuera
x = 20
def  my_funct(numero):
  x = numero
  return x

print(my_funct(10))
print(x)

10
20


In [0]:
#puedo reutilizar variables definidas afuera de la función
def  my_funct(numero):
  
 
  return x+numero

my_funct(10)

30

In [0]:
#Con "global" las declaraciones dentro de la función al ejecutarse pueden cambiar al valor original de la variable definida a fuera de la función
#En general no se recomiendo el uso de "global"
def  my_funct(numero):
  global x
  x = numero
  return x

print(x) #x antes
my_funct(10) #ejecutar función sobre x
print(x) #x después

20
10


## 2.3 Programación orientada a objetos (OOP)



1. Clase: Propiedad y comportamiento de un objeto concreto.
2. Objeto: Instancia de una clase
3. Atributo: Propiedad del objeto
4. Método: Lo que un objeto puede hacer 



Más documentación<br><br>
Métodos especiales: https://docs.python.org/3/reference/datamodel.html#special-method-names<br>


In [0]:
'hola {nombre}'.format(nombre='Diego')

'hola Diego'

In [0]:
class Book():
  
    #Método constructor: Función para instanciar un objeto. 
    def __init__(self, title, author, pages): 
        print("A book is created") #mensaje que se muestra en patalla al crear un objeto
        
        #Atributos de cada objeto
        self.title = title 
        self.author = author
        self.pages = pages

    #Métodos especiales
    def __str__(self): #al utilizar la función print() sobre un objeto retorna un string con todos sus atributos de forma. sin este método al imprimir un objeto este se 
        return "Title:%s , author:%s, pages:%s " %(self.title, self.author, self.pages)

    def __len__(self):#al utilizar la función len() sobre un objeto retorna el número de páginas del libro
        return self.pages

        
    #método    
    def saludar(self, saludo):
      return '{s} {autor}'.format(s=saludo, autor=self.author)



In [0]:
# instanciar un objeto
book = Book("Machine Learning A Probabilistic Perspective", "K. Murphy", 1000) 

A book is created
A book is destroyed


In [0]:
book

In [0]:
#Acceder a un atributo de un objeto
book.title

'Machine Learning A Probabilistic Perspective'

In [0]:
#Método especial: print
print(book)

Title:Machine Learning A Probabilistic Perspective , author:K. Murphy, pages:1000 


In [0]:
#Método especial:len
len(book)


1000

In [0]:
#Método normal
book.saludar('Hola')

'Hola K. Murphy'

# 3. Python Level 3


Instalar librerías en python, comandos: pip y conda

Más documentación:

https://packaging.python.org/tutorials/installing-packages/

https://conda.io/docs/user-guide/tasks/manage-pkgs.html#installing-packages




## 3.1 Numpy

100 numpy exercises

https://drive.google.com/file/d/1GeqpxhbqXDv1Fq8GshnbdP6oUvpxSQv9/view



In [0]:
# as: renombrar librería importada
import numpy as np

In [0]:
#python crea los vectores como vectores fila
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [0]:
#largo del vector
len(a)

3

In [0]:
#dimensión del vector
a.shape

(3,)

In [0]:
#matriz de una fila con tres columnas
b = np.array([[1, 2, 3]])
b

array([[1, 2, 3]])

In [0]:
b.shape

(1, 3)

In [0]:
#vector columna

c = b.T #el método T transpone un objeto array
c

array([[1],
       [2],
       [3]])

Matrices con listas

In [0]:
#dos filas y tres columnas
matriz = [[1,2,3], [2,2,2]]
print(matriz)
#primera fila
print(matriz[0])

#tercera columna
print([elem[2] for elem in matriz])

[[1, 2, 3], [2, 2, 2]]
[1, 2, 3]
[3, 2]


Matrices con numpy

In [0]:
#matriz de dos filas y tres columnas
matriz = np.array([[1, 2, 3], [2, 2, 2]])
matriz

array([[1, 2, 3],
       [2, 2, 2]])

In [0]:
#elemento que esta en la primera fila y última columa
matriz[0][2]

3

In [0]:
#primera fila
matriz[0]

array([1, 2, 3])

In [0]:
#primera columna
matriz[:, 1]

array([1, 2, 3])

In [0]:
matriz[:][0:2]

array([[1, 2, 3],
       [2, 2, 2]])

In [0]:
#largo de la matriz = número de filas
len(matriz)

2

In [0]:
#dimensión de la matriz
matriz.shape

(2, 3)

In [0]:
a=np.array([1,2,3])
b=np.array([2,2,2])

print('Producto cruz: ', a*b)
print('Producto punto: ', np.dot(a, b))

Producto cruz:  [2 4 6]
Producto punto:  12


In [0]:
#Producto matricial, la dimensión de las matrices debe ser: n1 x m y m x n2
np.dot(matriz, c)

array([[14],
       [12]])

In [0]:
np.exp(2)

7.38905609893065

In [0]:
np.pi

3.141592653589793

In [0]:
np.log(1)

0.0

In [0]:
print("mínimo de 'a': ", a.min())
print("máximo de 'a': ", a.max())
print("promedio de'a': ", a.mean())
print("desviación de 'a': ", a.std())

mínimo de 'a':  1
máximo de 'a':  3
promedio de'a':  2.0
desviación de 'a':  0.816496580927726
